language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - nightly
  - hhvm

env:
  global:
    - PATH="$HOME/.composer/vendor/bin:$PATH"

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: CS_FIXER=run
    - php: 5.4
      env: COMPOSER_FLAGS="--prefer-lowest"
  allow_failures:
    - php: 7.0
    - php: nightly
    - php: hhvm

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.composer/vendor

before_script:
  - composer selfupdate
  - composer config -g github-oauth.github.com $GITHUB_OAUTH_TOKEN
  - composer global require phpunit/phpunit fabpot/php-cs-fixer --no-update
  - composer global update --prefer-dist --no-interaction
  - composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
  - if [ "$CS_FIXER" = "run" ]; then make cs_dry_run ; fi;
  - make test
